services:
  - type: web
    name: copimon-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: COPIMON_DB
        value: copimon.sqlite


